title: Hiep Le's Tech Notes
github_username:  lenguyenhaohiep
linkedin_username: hiep-le-20450162

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
permalink: /:categories/:title/
paginate: 8
